### ISSUE TITLE
Tokenizing `-0` as negative zero was a mistake in the CSS specification

### ISSUE THREAD

**Issue by romainmenke** [keithamus/csslex#1]
https://github.com/keithamus/csslex/blob/214bf6fa1145563509a09a6f4ad41028fb302234/test-rmenke-css-tokenizer-tests.js#L35-L36

see : https://github.com/w3c/csswg-drafts/issues/7472

I still need to update our tokenizer in `@csstools/css-tokenizer` and the tests package.

**Comment by keithamus** [comment]
Thanks for this!
