### ISSUE TITLE
`1e+` is parsed incorrectly

### ISSUE THREAD

**Issue by romainmenke** [keithamus/csslex#6]
This should be parsed as a dimension with a unit of `e` followed by a delim token `+`.
I didn't verify this with the specification, so maybe good to review relevant sections.

https://github.com/romainmenke/css-tokenizer-tests/blob/main/CHANGELOG.md#111

**Comment by keithamus** [comment]
Yep this looks correct. 

> If the [next 2 or 3 input code points](https://drafts.csswg.org/css-syntax/#next-input-code-point) are U+0045 LATIN CAPITAL LETTER E (E) or U+0065 LATIN SMALL LETTER E (e), optionally followed by U+002D HYPHEN-MINUS (-) or U+002B PLUS SIGN (+), followed by a [digit](https://drafts.csswg.org/css-syntax/#digit), then:

My reading is that it _must_ include both the plus sign and the digit to continue parsing the exponent.

**Comment by keithamus** [comment]
Thanks! This is now released as https://github.com/keithamus/csslex/releases/tag/v1.0.3

**Comment by romainmenke** [comment]
Awesome!

**Comment by keithamus** [comment]
@romainmenke also noticed https://github.com/romainmenke/css-tokenizer-tests/commit/3b31516cd9147f6d19d748dcc0cf80bf9ac145a8 so I've released https://github.com/keithamus/csslex/releases/tag/v1.0.4 to fix that 😉

**Comment by romainmenke** [comment]
Haha, was just filing an issue 🙇 

I've switched the fuzzer to compare with `csslex` but it tends to find issues one by one :)

**Comment by romainmenke** [comment]
After ±3 million randomly generated bits of CSS I am fairly certain that there are no more issues 🎉
